### PR TITLE
Fixed lack of support for primitive type constraints

### LINKED ISSUE #92: Need --skip argument for javadoc
I'm hitting a crash that seems to originate in the javadoc exporter (see traceback below). I realized I could get around it if I could skip that export. But the only "skips" are json, fhir, and all. I could use "all" but then I can't test the FHIR maps. So there are two things: (1) add the skip argument for every exporter, (2) fix the crash.  Here's the traceback: 
```
C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:153
    var constraintName = (this.field.valueType === 'RefValue') ? `ref(${element.name})` : element.name;
                                                                                                 ^

TypeError: Cannot read property 'name' of undefined
    at Constraints.typeConstraint (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:153:98)
    at Constraints.switchConstraintType (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:214:12)
    at Object.keys.forEach (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:234:14)
    at Array.forEach (native)
    at Constraints.parse (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:232:43)
    at new Constraints (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\constraints.js:35:10)
    at element.fields.forEach (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\elements.js:144:18)
    at Array.forEach (native)
    at Elements.updateFields (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\elements.js:128:20)
    at list.forEach (C:\Users\mkramer\Documents\GitHub\shr-cli-5.7.2\node_modules\shr-json-javadoc\components\elements.js:160:12)
```

### PR DESCRIPTION
**Pull request by Abhijay**
Fixed: https://github.com/standardhealth/shr-cli/issues/92

Before, type constraints were assumed to lead to element definitions. This lead to a crash in the tooling.
This update fixes that assumption.

### CODE REVIEW

File: components/constraints.js [hunk 1]
```diff
@@ -149,13 +149,22 @@ class Constraints {
...
+
     const element = this.elements[constraint.fqn];
-    var constraintName = (this.field.valueType === 'RefValue') ? `ref(${element.name})` : element.name;
-    if (this.field.valueType === 'RefValue') {
-      constraintName = `${constraintName}`;
-    }
+    if (element) {
+      constraintName = (this.field.valueType === 'RefValue') ? `ref(${element.name})` : element.name;
+      if (this.field.valueType === 'RefValue') {
+        constraintName = `${constraintName}`; //TODO: This doesn't do anything...
```
Comment (cmoesel) [inline components/constraints.js]: This obviously (as confirmed by the TODO) doesn't do anything -- but what is the intent?  Why is this code here at all?

Comment (Abhijay) [reply components/constraints.js]: Honestly, no idea. It looks like it might've been leftover special logic code from when this tool was first written (that I didn't write). 

I planned on removing it, although I wasn't sure if I should touch it during this bug fix (in case there's some reason for its existence), or if I should save it for a later code clean-up/refactor.

Comment (cmoesel) [reply components/constraints.js]: I say kill it.

Comment (Abhijay) [reply components/constraints.js]: Done.

**Comment by cmoesel** [comment]
Verified I could reproduce the crash without the fix and then confirmed that there is no crash with the fix.  Looks good!

**Review by cmoesel — APPROVED** [review]
